---

clientid: teemdev
instance_group_name: teemnz
#AWS private key for accessing credentials on server
key_name: "teemdev"
#non paramater variables
vpc_subnet_id: "subnet-3c47c84b"
security_group_ids:
  - "sg-ba5a06df"
region: "ap-southeast-2"
dnszone: dev.teemops.com
amibase:
  www: "ami-f53679cf"

#configurable as parameters
base_name: teemnz
instance_type: t2.micro
git_project: website
git_base_repo_url: git@bitbucket.org:teemnz
git_ssh_key: teem_deploy
assign_public_ip: true
assign_eip: false

# Instance Specific Tags and Volumes

#instance_profile_name: "{{ instance_profile_name }}"
www_instance_tags:
  Name: "www.{{base_name}}.{{dnszone}}"
  Product: website

# volumes
# /dev/sda1 = /
# /dev/xvdf = /optionalpath
www_volumes:
  - device_name: /dev/sda1
    device_type: gp2
    volume_size: 30 #Must be at least 30Gb for Windows VOL Snapshots, 8GB for most Linux VOL Snapshots
    delete_on_termination: true
