---
# New Relic PHP Agent Deployment
- apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present
- command: apt-add-repository "deb http://apt.newrelic.com/debian/ newrelic non-free"

- apt: update_cache=yes

- name: Install New Relic PHP Agent
  apt: pkg={{item}} state=present
  with_items:
      - newrelic-php5

- command: echo newrelic-php5 newrelic-php5/application-name string "{{newrelic_app}}" | debconf-set-selections
- command: echo newrelic-php5 newrelic-php5/license-key string "{{newrelic_license}}" | debconf-set-selections

# Restart the PHP and NGINX
- name: restart services
  service: name={{item}} state=restarted
  with_items:
      - php5-fpm
      - nginx