---

- name: Launch EC2
  hosts: localhost
  sudo: false
  vars_files:
    - vars/common.yml
    - vars/customers/teem-dev.yml
    
  roles:

    - sitecore.init
    #Dev Build.
    - { role: ec2, islinux: true, instance_group_name: "cms", myec2: "www", ami: "{{ amibase.www }}", ec2_instance_tags: "{{www_instance_tags}}", ec2_volumes: "{{www_volumes}}", bootstrap_script_contents: "{{sitecore_bootstrap}}" }
    - { role: route53, instance_name_tag:  "{{ www_instance_tags.Name }}" }
    #add the standalone to sql, authoring and content
    - { role: addtohostgroup, ip_to_add: "{{ec2.tagged_instances[0].private_ip}}", group_to_add: "www"}


# This playbook deploys the entire PHP stack
- name: Run PHP playbook - installs PHP and a sample PHP app
  hosts: all
  user: ubuntu

  vars_files:
    - vars/common.yml
    - vars/customers/teem-dev.yml 
     
  roles:
    - ssh
    - php56
    #- monitor_newrelic_php
    - mysql
    - code
    - app_wordpress
